blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/openhiveprotocol/hive/discussions
    about: Ask and answer questions with the community.
  - name: Report a security vulnerability
    url: https://github.com/openhiveprotocol/hive/security/policy
    about: Please report security vulnerabilities responsibly.